#!/usr/bin/bash
#file name: deskmac
#open virtalmachine  deskmac and ssh on it


if ! nc -zw1 deskmac 22 >/dev/null 2>&1;then
    echo deskmac is starting...
    if [ "$#" -eq 0 ];then
        echo "now is no graphic mode"
        echo "'deskmac xx' graphic mode"
        HEADLESS=1 /home/jiayi/gitsource/OneClick-macOS-Simple-KVM/basic.sh >/dev/null &
    else  
        /home/jiayi/gitsource/OneClick-macOS-Simple-KVM/basic.sh &
    fi
fi

timeout=0
while ! nc -zw1 deskmac 22 >/dev/null 2>&1;do
    echo -n '.'
    let timeout++
    if [ "$timeout" -gt 60 ];then
        echo ""
        echo  "connecting timeout."
        exit
    fi
done
echo -e "\n\n"
sshpass -p zjy85295675 ssh  jiayi@deskmac
