#!/usr/bin/bash
#file name: kali
#open virtalmachine kali and ssh on it
name=$(virsh list --name)
name=${name:-None}
if [ $name = "kali" ]
then
	sshpass -p kali ssh kali@kali
else
	echo "'kali' is starting..."
	virsh start kali
	return=$?
	if [ $return = '1'  ]
	then
		echo "can not find virtalmachine 'kal',please check."
		exit $return
	fi
	if [ $return = '127'  ]
	then
		echo "'virsh' not installed.please install it and try againt."
		exit $return
	fi
	if [ $return = '0'  ]
	then
		echo "connecting kali..."
		echo -n "please waitting about 9 sec."
		for (( i=9;i>0;i-- ));
		do echo -en "\b\b\b\b\b\b${i} sec."
			sleep 1
		done
		echo -e "\b\b\b\b\b\b0 sec."
		sshpass -p kali ssh kali@kali
	else
		echo "'kali'has something worong,exit."
		echo "return $return"
		exit $return
	fi
fi

