#!/usr/bin/bash
#file name: loadfile
#implement loadfile of jlinkexe to simplify using burnning *.hex to stm32f mcu
JLINK=$(which JLink.exe)
if [ -z "$JLINK" ]
then
JLINK=$(which JLinkExe)
	if [ -z "$JLINK" ]
	then
		echo "can not find jlink,it may be not installed."
		exit 1
	else
		JLINK='JLinkExe'
	fi
else
JLINK='JLink.exe'
fi
if [ ! -f $1 ]
then
	echo file is not exist.
	exit 1
fi
COMMANDFILE=.jlink
echo 'h'> $COMMANDFILE
echo 'r'> $COMMANDFILE
echo "loadfile $1" >> $COMMANDFILE
echo 'r'  >> $COMMANDFILE
echo 'g'  >> $COMMANDFILE
echo 'qc' >> $COMMANDFILE
$JLINK -autoconnect 1 -device stm32f407ve -if swd -speed 400 -commandfile $COMMANDFILE
rm -f $COMMANDFILE
