#!/usr/bin/bash
#file name: loadfile
#implement loadfile of jlinkexe to simplify using burnning *.hex to stm32f mcu
JLINK=$(which JLink.exe)
if [ -z "$JLINK" ]
then
JLINK=$(which JLinkExe)
	if [ -z "$JLINK" ]
	then
		echo "can not find jlink,it may be not installed.">&2
		exit 1
	else
		JLINK='JLinkExe'
	fi
else
JLINK='JLink.exe'
fi
if [ ! -f "$1" ]
then
	echo "file '$1' is not exist!">&2
	exit 1
fi
COMMANDFILE=.jlink
ADDR="$2"
if [ -z "$2" ];then
	echo "address not input!">&2
elif [[ "$2" =~ ^0[Xx]8[[:digit:]]{6} ]];then
	echo 'h'>"$COMMANDFILE"
	echo 'h'>"$COMMANDFILE"
	echo "loadbin $1 $2">>"$COMMANDFILE"
	echo 'r'>>$COMMANDFILE
	echo 'g'>>$COMMANDFILE
	echo 'qc'>>$COMMANDFILE
	"$JLINK" -autoconnect 1 -device stm32f407ve -if swd -speed 400 -commandfile $COMMANDFILE
	rm -f "$COMMANDFILE"
else
	echo "the address input is not correct!">&2
	echo "should input like 0x8000000.">&2
fi
	
	
