#!/usr/bin/bash
#file name: vm_mac
#open virtalmachine  vm_mac and ssh on it


if ! nc -zw1 vm_mac 22 >/dev/null 2>&1;then
    echo vm_mac is starting...
    if [ "$#" -eq 0 ];then
        echo "now is no graphic mode"
        echo "'vm_mac xx' graphic mode"
        HEADLESS=1 /home/jiayi/gitsource/OneClick-macOS-Simple-KVM/basic.sh >/dev/null &
    else  
        /home/jiayi/gitsource/OneClick-macOS-Simple-KVM/basic.sh &
    fi
fi

while ! nc -zw1 vm_mac 22 >/dev/null 2>&1;do
    echo -n '.'
done
echo -e "\n\n"
sshpass -p zjy85295675 ssh  black@vm_mac
